services:
  server-1:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app

  server-2:
    build: ./server-2
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app-2

  hw-gateway:
    build: ./gateway-1
    ports:
      - "4001:4001"
    volumes:
      - ./gateway-1:/app/gateway-1

  postgresql-master:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresql_master_data:/bitnami/postgresql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=development_database
      - ALLOW_EMPTY_PASSWORD=yes

  postgresql-slave:
    image: bitnami/postgresql
    restart: always
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

  prisma:
    image: prismagraphql/prisma:latest
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - postgresql-master
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgresql
            host: postgresql-master
            port: 5432
            user: postgres
            password: postgres
            migrations: true
            database: development_database
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgresql_master_data:
    driver: local
