export const dummyAiResponse = {
  form_name: "Coal Mine Blasting Operation Record",
  form_description:
    "Comprehensive documentation of coal mine blasting operations, adhering to Indian mining safety standards.",
  sections: [
    {
      section_name: "General Information",
      section_description: "Basic details about the blasting operation.",
      fields: [
        {
          label: "Mine Name",
          name: "mine_name",
          type: "Text",
          description: "Name of the coal mine.",
          placeholder: "Enter mine name",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Date",
          name: "date",
          type: "Date Picker",
          description: "Date of the blasting operation.",
          placeholder: "Select date",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Time",
          name: "time",
          type: "Datetime Picker",
          description: "Time of the blasting operation.",
          placeholder: "Select time",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Shift",
          name: "shift",
          type: "Select",
          description: "Shift during which blasting occurred.",
          placeholder: "Select shift",
          required: true,
          value: "",
          checked: true,
          options: [
            {
              label: "Day",
              value: "day",
            },
            {
              label: "Night",
              value: "night",
            },
          ],
        },
        {
          label: "Location",
          name: "location",
          type: "Text",
          description: "Specific location within the mine (e.g., pit, seam).",
          placeholder: "Enter location",
          required: true,
          value: "",
          checked: true,
        },
      ],
    },
    {
      section_name: "Technical Details",
      section_description: "Specifics of the blasting procedure.",
      fields: [
        {
          label: "Blast Design",
          name: "blast_design",
          type: "Textarea",
          description: "Details of the blast design.",
          placeholder: "Enter blast design details",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Explosives Used",
          name: "explosives_used",
          type: "Text",
          description: "Type and quantity of explosives used.",
          placeholder: "Enter explosives details",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Number of Holes",
          name: "number_holes",
          type: "Number",
          description: "Total number of blast holes.",
          placeholder: "Enter number of holes",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Initiation System",
          name: "initiation_system",
          type: "Text",
          description: "Type of initiation system used.",
          placeholder: "Enter initiation system details",
          required: true,
          value: "",
          checked: true,
        },
      ],
    },
    {
      section_name: "Safety and Compliance",
      section_description: "Safety measures and regulatory adherence.",
      fields: [
        {
          label: "Pre-Blast Inspection",
          name: "pre_blast_inspection",
          type: "Textarea",
          description: "Details of the pre-blast inspection.",
          placeholder: "Enter pre-blast inspection details",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Safety Precautions",
          name: "safety_precautions",
          type: "Multi Select",
          description: "Safety precautions taken.",
          placeholder: "Select safety precautions",
          required: true,
          value: "",
          checked: true,
          options: [
            {
              label: "Warning signals",
              value: "warning_signals",
            },
            {
              label: "Evacuation procedures",
              value: "evacuation",
            },
            {
              label: "Dust suppression",
              value: "dust_suppression",
            },
          ],
        },
        {
          label: "Compliance Officer",
          name: "compliance_officer",
          type: "Text",
          description: "Name of the compliance officer.",
          placeholder: "Enter compliance officer name",
          required: true,
          value: "",
          checked: true,
        },
      ],
    },
    {
      section_name: "Post-Blast Assessment",
      fields: [
        {
          label: "Results of Blast",
          name: "blast_results",
          type: "Textarea",
          description: "Observations and measurements after the blast.",
          placeholder: "Enter blast results",
          required: true,
          value: "",
          checked: true,
        },
        {
          label: "Fragmentation Analysis",
          name: "fragmentation",
          type: "Text",
          description: "Assessment of rock fragmentation.",
          placeholder: "Enter fragmentation analysis",
          required: true,
          value: "",
          checked: true,
        },
      ],
    },
  ],
};
